version: '3.8'

services:
  redis-1:
    image: redis:7.0
    container_name: redis-1
    volumes:
      - ./redis/redis-1-redis.conf:/usr/local/etc/redis/redis.conf
      - ./nodes/redis-1-nodes.conf:/data/nodes.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.21

  redis-2:
    image: redis:7.0
    container_name: redis-2
    volumes:
      - ./redis/redis-2-redis.conf:/usr/local/etc/redis/redis.conf
      - ./nodes/redis-2-nodes.conf:/data/nodes.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.22

  redis-3:
    image: redis:7.0
    container_name: redis-3
    volumes:
      - ./redis/redis-3-redis.conf:/usr/local/etc/redis/redis.conf
      - ./nodes/redis-3-nodes.conf:/data/nodes.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.23

  redis-4:
    image: redis:7.0
    container_name: redis-4
    volumes:
      - ./redis/redis-4-redis.conf:/usr/local/etc/redis/redis.conf
      - ./nodes/redis-4-nodes.conf:/data/nodes.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.24

  redis-5:
    image: redis:7.0
    container_name: redis-5
    volumes:
      - ./redis/redis-5-redis.conf:/usr/local/etc/redis/redis.conf
      - ./nodes/redis-5-nodes.conf:/data/nodes.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.25

  redis-6:
    image: redis:7.0
    container_name: redis-6
    volumes:
      - ./redis/redis-6-redis.conf:/usr/local/etc/redis/redis.conf
      - ./nodes/redis-6-nodes.conf:/data/nodes.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.26


networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16