package k8smeta

import (
	"maps"

	"strconv"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ExporterPortProvider returns the exporter port if bool is true
type ExporterPortProvider func() (port int, enable bool)

var DisableMetrics ExporterPortProvider = func() (int, bool) {
	return 0, false
}

func GenerateServiceAnots(serviceMeta metav1.ObjectMeta, additionalAnnotations map[string]string, epp ExporterPortProvider) map[string]string {
	anots := map[string]string{
		"redis.ej.com":          "true",
		"redis.ej.com/instance": serviceMeta.GetName(),
	}

	// Only annotate scrape metadata when the Service actually exposes exporter metrics.
	if epp != nil {
		if exporterPort, ok := epp(); ok {
			anots["prometheus.io/scrape"] = "true"
			anots["prometheus.io/port"] = strconv.Itoa(exporterPort)
		}
	}

	maps.Copy(anots, serviceMeta.GetAnnotations())
	maps.Copy(anots, additionalAnnotations)
	return filterAnnotations(anots)
}

func GenerateStatefulSetsAnots(stsMeta metav1.ObjectMeta) map[string]string {
	anots := map[string]string{
		"redis.ej.com":          "true",
		"redis.ej.com/instance": stsMeta.GetName(),
	}
	maps.Copy(anots, stsMeta.GetAnnotations())
	return filterAnnotations(anots)
}

// filterAnnotations Remove autogenerated annotations which pose no use to downstream objects (Services,Pods,etc)
func filterAnnotations(anots map[string]string) map[string]string {
	// Filter out some problematic annotations we don't want in the template.
	delete(anots, "kubectl.kubernetes.io/last-applied-configuration")
	delete(anots, "banzaicloud.com/last-applied")

	return anots
}
