# redis-6 (172.20.0.16) - slave of redis-2
# ⚠️ 일부러 틀린 IP! 실제 IP는 172.20.0.16인데 100으로 설정
# nodes.conf에는 172.20.0.16이 적혀있음 → redis.conf vs nodes.conf 누가 이길까?
port 6379
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
cluster-announce-ip 172.20.0.26
