package helper

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func GenerateStatefulSetsAnots(stsMeta metav1.ObjectMeta, ignoreAnnots []string) map[string]string {
	anots := map[string]string{
		"redis.opstreelabs.in":       "true",
		"redis.opstreelabs.instance": stsMeta.GetName(),
	}
	for k, v := range stsMeta.GetAnnotations() {
		anots[k] = v
	}
	return filterAnnotations(anots, ignoreAnnots...)
}

// filterAnnotations Remove autogenerated annotations which pose no use to downstream objects (Services,Pods,etc)
func filterAnnotations(anots map[string]string, ignoreAnnots ...string) map[string]string {
	// Filter out some problematic annotations we don't want in the template.
	delete(anots, "kubectl.kubernetes.io/last-applied-configuration")
	delete(anots, "banzaicloud.com/last-applied")

	for _, ignoreAnnot := range ignoreAnnots {
		delete(anots, ignoreAnnot)
	}

	return anots
}
