fullnameOverride: rediscluster
controllerManager:
  manager:
    args:
    - manager
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    image:
      repository: redis-operator
      tag: v1.0.4
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    env:
      initContainerImage: redis-operator:v1.0.4
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ""
