apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: redis-alerts
  namespace: default
  labels:
    alertmanagerConfig: redis
spec:
  route:
    receiver: redis-webhook
    groupBy:
      - alertname
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    matchers:
      - name: alertname
        matchType: "=~"
        value: "^Redis.*"
  receivers:
    - name: redis-webhook
      webhookConfigs:
        - urlSecret:
            name: redis-alert-webhook
            key: url
          sendResolved: true
